echo "START NEW RENDER..."
CITY=$1
MOBILITY_TYPE=$2
ID=$3
PATH_TO_FILE_FOLDER=data/"$CITY"/"$MOBILITY_TYPE"
PATH_TO_FILE_MP4="$PATH_TO_FILE_FOLDER"/"$ID".mp4
PATH_TO_FOLDER_TEMP_FRAME="$PATH_TO_FILE_FOLDER"/frames_street_"$ID"
PATH_S3_BUCKET="$CITY"/"$MOBILITY_TYPE"/"$ID".mp4

echo "RENDERING FRAMES FOR $PATH_TO_FILE_MP4 ..."
rm -rf $PATH_TO_FOLDER_TEMP_FRAME
phantomjs record.js $CITY $MOBILITY_TYPE $ID
echo "IF RENDERING FRAMES SUCCESS, FFMPEG WILL MAKE THAT A MP4, IF NOT WILL FAIL AND GO THE NEXT ONE ..."
ffmpeg -y -r 20 -f image2 -s 512x512 -i ${PATH_TO_FOLDER_TEMP_FRAME}/frame_%d.png -vcodec libx264 -crf 25  -pix_fmt yuv420p $PATH_TO_FILE_MP4
echo "CLEAN UP FRAMES ..."
rm -rf $PATH_TO_FOLDER_TEMP_FRAME
# echo "TRIGGER UPLOAD MP4 TO S3, if file wasn't render it will fail and go to next one"
# node uploadS3.js $PATH_TO_FILE_MP4 $PATH_S3_BUCKET
echo "FINISH RENDER ..."
