export const LOAD_CITIES_REQUEST = 'App/City/LOAD_CITIES_REQUEST';
export const LOAD_CITIES_SUCCESS = 'App/City/LOAD_CITIES_SUCCESS';
export const LOAD_CITIES_FAILURE = 'App/City/LOAD_CITIES_FAILURE';
export const SELECT_CITY = 'App/City/SELECT_CITY';
export const TOGGLE_CITY_SELECTION = 'App/City/TOGGLE_CITY_SELECTION';
export const SET_NEAREST_CITY = 'App/City/SET_NEAREST_CITY';
