export const NEXT_SCROLL_INDEX = 'App/NEXT_SCROLL_INDEX';
export const PREVIOUS_SCROLL_INDEX = 'App/PREVIOUS_SCROLL_INDEX';
export const SCROLLING = 'App/SCROLLING';
export const SET_SCROLL_INDEX = 'App/SET_SCROLL_INDEX';
export const REGISTER_SCROLL_TARGET = 'App/REGISTER_SCROLL_TARGET';
export const FINISH_SCROLLING = 'App/FINISH_SCROLLING';
